FROM oven/bun:1-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY apps/frontend/package.json apps/frontend/package.json
COPY apps/frontend/tsconfig.json apps/frontend/tsconfig.json
COPY packages packages

RUN bun install

COPY apps/frontend apps/frontend

RUN bun run frontend:build

EXPOSE 3000

CMD [ "bun", "run", "frontend:start" ]