FROM oven/bun:1-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY apps/backend/package.json apps/backend/package.json
COPY apps/backend/tsconfig.json apps/backend/tsconfig.json

RUN bun run install

COPY apps/backend apps/backend
COPY packages packages

RUN bun run db:generate
RUN bun run backend:build

CMD [ "bun", "run", "backend:start" ]